// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE7_gYf1UZ-KgfRS45xPKYkAy0S5GxYbk',
    appId: '1:968103235749:web:403b7c7a79c3846fedbd4c',
    messagingSenderId: '968103235749',
    projectId: 'mymedicosupdated',
    authDomain: 'mymedicosupdated.firebaseapp.com',
    databaseURL: 'https://mymedicosupdated-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mymedicosupdated.appspot.com',
    measurementId: 'G-B66D4LFS4J',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE7_gYf1UZ-KgfRS45xPKYkAy0S5GxYbk',
    appId: '1:968103235749:web:a86acbaab8da9c1bedbd4c',
    messagingSenderId: '968103235749',
    projectId: 'mymedicosupdated',
    authDomain: 'mymedicosupdated.firebaseapp.com',
    databaseURL: 'https://mymedicosupdated-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mymedicosupdated.appspot.com',
    measurementId: 'G-D393QNLV77',
  );
}
